from tkinter import *
window = Tk()
window.geometry("250x400")
buttons=Frame(window)

text=StringVar()
entry= Entry(window,font=("digital-7",40),width=buttons.winfo_screenwidth(),bg="green",textvariable=text)
entry.pack()
buttons.pack()
def type(x):
    entry.insert(len(entry.get())+1,x)
def equal():
    try:
        
        solution=str(eval(entry.get()))
        text.set(solution)
    except SyntaxError:
        text.set("syntax error")
    except ZeroDivisionError:
        text.set("arithmetic error")

def clear():
    text.set("")
def backspacef():
    entry.delete(len(entry.get())-1,END)
button1=Button(buttons,text="1",font=("Ariel",25),command=lambda:type(1))
button1.grid(row=0,column=0)
button2=Button(buttons,text="2",font=("Ariel",25),command=lambda:type(2))
button2.grid(row=0,column=1)
button3=Button(buttons,text="3",font=("Ariel",25),command=lambda:type(3))
button3.grid(row=0,column=2)
button4=Button(buttons,text="4",font=("Ariel",25),command=lambda:type(4))
button4.grid(row=1,column=0)
button5=Button(buttons,text="5",font=("Ariel",25),command=lambda:type(5))
button5.grid(row=1,column=1)
button6=Button(buttons,text="6",font=("Ariel",25),command=lambda:type(6))
button6.grid(row=1,column=2)
button7=Button(buttons,text="7",font=("Ariel",25),command=lambda:type(7))
button7.grid(row=2,column=0)
button8=Button(buttons,text="8",font=("Ariel",25),command=lambda:type(8))
button8.grid(row=2,column=1)
button9=Button(buttons,text="9",font=("Ariel",25),command=lambda:type(9))
button9.grid(row=2,column=2)
button0=Button(buttons,text="0",font=("Ariel",25),command=lambda:type("0"))
button0.grid(row=3,column=1)
buttonplus=Button(buttons,text="+",font=("Ariel",25),command=lambda:type("+"))
buttonplus.grid(row=0,column=3)
buttonmultiply=Button(buttons,text="*",font=("Ariel",25),command=lambda:type("*"))
buttonmultiply.grid(row=1,column=3)
buttondivison=Button(buttons,text="/",font=("Ariel",25),command=lambda:type("/"))
buttondivison.grid(row=2,column=3)
buttonequal=Button(buttons,text="=",font=("Ariel",25),command=equal)
buttonequal.grid(row=3, column=2)
buttonclear=Button(buttons,text="C",font=("Ariel",25),command=clear)
buttonclear.grid(row=4,column=0)
buttondot=Button(buttons,text=".",font=("Ariel",25),command=lambda:type("."))
buttondot.grid(row=3,column=0)
buttonminus=Button(buttons,text="-",font=("Ariel",25),command=lambda:type("-"))
buttonminus.grid(row=3,column=3)
paranthesisl=Button(buttons,text="(",font=("Ariel",25),command=lambda:type("("))
paranthesisl.grid(row=4,column=2)
paranthesisr=Button(buttons,text=")",font=("Ariel",25),command=lambda:type(")"))
paranthesisr.grid(row=4,column=3)
backspace=Button(buttons,text="⌫",font=("Ariel",25),command=backspacef)
backspace.grid(row=4,column=1)
window.mainloop()